(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.NordicWatchIntelligence=api})(globalThis,function(){
'use strict';
const H=3600000, iso=v=>v!=null&&v!==''&&Number.isFinite(+new Date(v))?new Date(v).toISOString():null;
const norm=v=>String(v||'').normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const list=v=>[...new Set((Array.isArray(v)?v:v&&typeof v==='object'?Object.values(v).flat():v?[v]:[]).map(x=>norm(typeof x==='object'?JSON.stringify(x):x)))].sort();
function hash(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function canonical(value){try{const u=new URL(value);u.hash='';for(const k of [...u.searchParams.keys()])if(/^(utm_|fbclid|gclid)/i.test(k))u.searchParams.delete(k);u.searchParams.sort();return u.href.replace(/\/$/,'')}catch{return ''}}
function signal(raw,now=Date.now(),previous){const publishedAt=iso(raw.publishedAt||raw.articlePublishedAt),ingestedAt=previous?.ingestedAt||iso(raw.ingestedAt)||iso(now),eventTime=iso(raw.eventTime||raw.eventOccurredAt||raw.temporal?.eventOccurredAt)||publishedAt||ingestedAt;
 const effective=raw.temporal?.containsNewDevelopment?publishedAt||ingestedAt:eventTime;
 const expiresAt=iso(Math.min(+new Date(effective)+24*H,+new Date(publishedAt||ingestedAt)+24*H));
 const age=Math.max(0,(now-+new Date(effective))/H),freshness=age<24?'FRESH':age<=72?'RECENT':'HISTORICAL';
 return {...raw,signalId:previous?.signalId||raw.signalId||'signal-'+hash(canonical(raw.url||raw.sourceUrl)||norm(raw.title)),publishedAt,ingestedAt,lastUpdatedAt:iso(raw.lastUpdatedAt)||publishedAt||ingestedAt,eventTime,expiresAt,freshness,timeStatus:publishedAt?'KNOWN':'TIME_UNCERTAIN',confidence:publishedAt?(raw.confidence??65):Math.min(40,Number(raw.confidence)||40)};
}
function decay(s,now=Date.now()){const h=Math.max(0,(now-+new Date(s.temporal?.containsNewDevelopment?s.publishedAt||s.ingestedAt:s.eventTime||s.publishedAt||s.ingestedAt))/H);return h<12?1:h<24?.75:h<48?.4:h<=72?.15:0}
function same(a,b){if(canonical(a.url||a.sourceUrl)&&canonical(a.url||a.sourceUrl)===canonical(b.url||b.sourceUrl))return true;const x=norm(a.title),y=norm(b.title);if(x===y)return true;const words=new Set(x.split(' ')),other=new Set(y.split(' ')),similar=[...words].filter(w=>other.has(w)).length/Math.max(words.size,other.size);return similar>=.88&&norm(a.eventType)===norm(b.eventType)&&norm(a.location||a.region)===norm(b.location||b.region)&&list(a.entities).join()===list(b.entities).join()&&Math.abs(+new Date(a.eventTime)-+new Date(b.eventTime))<24*H}
function ingest(previous,incoming,now=Date.now()){const rows=[...previous];for(const raw of incoming){const i=rows.findLastIndex(x=>same(x,raw)),old=rows[i],s=signal(raw,now,old);const revision=old&&(raw.containsNewDevelopment===true||raw.temporal?.containsNewDevelopment===true)&&+new Date(s.lastUpdatedAt)>+new Date(old.lastUpdatedAt)&&norm(raw.title+" "+raw.description)!==norm(old.title+" "+old.description);if(revision){s.signalId=old.signalId+"-"+hash(s.lastUpdatedAt);s.eventId=old.eventId;s.ingestedAt=iso(now);rows.push(s)}else if(old){s.eventTime=old.eventTime;s.publishedAt=old.publishedAt;s.lastUpdatedAt=old.lastUpdatedAt;s.eventId=old.eventId;rows[i]=signal({...old,...s},now,old)}else{ s.eventId=raw.eventId||'event-'+hash(norm(raw.title)+'|'+norm(raw.location||raw.region));rows.push(s)}}return rows.map(s=>signal(s,now,s))}
const persistent=/exercise|deployment|blockade|maritime|naval|gnss|infrastructure|conflict/;
function status(e,now=Date.now()){const start=+new Date(e.startDate||e.startTime),end=+new Date(e.endDate||e.endTime),last=+new Date(e.lastObservedAt||e.temporal?.eventOccurredAt||e.temporal?.articlePublishedAt||e.updatedAt||e.startTime);if(now<start)return 'UPCOMING';if(Number.isFinite(end)&&now>end)return 'ENDED';return now-last>(persistent.test(e.eventType)?Math.max(48*H,Number.isFinite(end)?end-last:7*24*H):48*H)?'INACTIVE':'ACTIVE'}
function event(raw,previous,now=Date.now()){const observed=iso(raw.lastObservedAt||raw.temporal?.eventOccurredAt||raw.temporal?.articlePublishedAt||raw.updatedAt||raw.startTime)||iso(now);const e={...previous,...raw,eventId:previous?.eventId||raw.eventId||raw.id,firstObservedAt:previous?.firstObservedAt||raw.firstObservedAt||observed,lastObservedAt:iso(Math.max(+new Date(previous?.lastObservedAt||observed),+new Date(observed))),startDate:raw.startDate||raw.startTime,endDate:raw.endDate||raw.endTime,locations:raw.locations||[raw.areaName].filter(Boolean),entities:raw.entities||raw.countries||[],sourceSignals:[...new Set([...(previous?.sourceSignals||[]),...(raw.sourceSignals||[])])],eventScore:raw.eventScore??raw.discovery?.score??0};e.status=status(e,now);return e}
function fingerprint(e){return JSON.stringify([e.eventType,e.status==='UPCOMING'?'PLANNED':e.status==='ACTIVE'?'ACTIVE':e.status,list(e.locations||[e.areaName]),list(e.entities||e.countries),list(e.organisations),list(e.expectedActivity),e.severity,e.confidence,e.escalation?.escalationLevel,e.radiusKm,list(e.confirmedSources),e.scope])}
function notification(e,previous,now=Date.now()){const f=fingerprint(e);return {shouldNotify:(!previous||previous.notificationFingerprint!==f)&&['ACTIVE','UPCOMING'].includes(e.status),record:{firstNotifiedAt:previous?.firstNotifiedAt||iso(now),lastNotifiedAt:iso(now),lastNotifiedVersion:(previous?.lastNotifiedVersion||0)+1,notificationFingerprint:f}}}
function changes(before,after){const rank={INFO:0,LOW:1,ELEVATED:2,MEDIUM:2,HIGH:3,CRITICAL:4};return after.flatMap(e=>{const p=before.find(x=>(x.eventId||x.id)===(e.eventId||e.id));let kind=!p?(['ACTIVE','UPCOMING'].includes(e.status)?'NEW':null):e.status!==p.status&&['ENDED','INACTIVE'].includes(e.status)?'ENDED':rank[e.severity]>rank[p.severity]?'ESCALATED':rank[e.severity]<rank[p.severity]?'DE-ESCALATED':e.confidence!==p.confidence&&/CONFIRMED|HIGH/.test(e.confidence)?'CONFIRMED':fingerprint(e)!==fingerprint(p)||e.eventScore!==p.eventScore?'UPDATED':null;return kind?[{kind,event:e,text:`${e.title} · ${kind}`}]:[]})}
function perimeter(e){const text=norm([e.title,e.description,e.region,e.areaName,...(e.countries||[])].join(' '));const flank=/schleswig holstein|mecklenburg vorpommern|kiel|rostock|lubeck|german baltic coast|gdansk|gdynia|szczecin|northern poland/.test(text),core=/sweden|swedish|finland|finnish|norway|norwegian|denmark|danish|estonia|latvia|lithuania|baltic sea|gotland|bornholm|gulf of finland|kaliningrad|murmansk|kola/.test(text),linked=/baltic|nordic|northern flank|suwalki|kaliningrad/.test(text);return {tier:flank?'BALTIC FLANK':core?'CORE':'EXTENDED CORRELATION',visible:flank||core||linked,reason:flank?'Baltic coastal security perimeter':core?'Nordic / Baltic security area':linked?'Explicit Baltic / Nordic connection':'No established Nordic / Baltic connection'}}
function cic(members){const days=new Set(members.map(x=>String(x.timestamp||x.eventTime).slice(0,10))).size,dimensions=new Set(members.map(x=>x.domain)),sources=new Set(members.map(x=>x.source||x.domain)),coherence=Math.min(1,days/3),interaction=Math.min(1,dimensions.size/3),corroboration=Math.min(1,sources.size/3);return {coherence,interaction,corroboration,score:Math.round(100*coherence*interaction*corroboration)}}
function signalEvents(signals,previous=[],now=Date.now()){const groups=new Map();for(const s of signals){const id=s.eventId;if(!id)continue;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(s)}return [...groups].map(([id,ss])=>{ss.sort((a,b)=>+new Date(a.eventTime)-+new Date(b.eventTime));const latest=ss.at(-1),old=previous.find(e=>e.eventId===id),times=ss.map(s=>(s.containsNewDevelopment||s.temporal?.containsNewDevelopment)?s.lastUpdatedAt:s.eventTime).sort(),e=event({id,eventId:id,title:latest.title,eventType:latest.eventType||'news_report',startTime:times[0],lastObservedAt:times.at(-1),sourceSignals:ss.map(s=>s.signalId),locations:latest.risk?.places?.map(p=>p.name)||[],entities:latest.entities||[],confidence:latest.timeStatus==='TIME_UNCERTAIN'?'LOW':latest.risk?.confidence||'LOW',severity:latest.risk?.severity||'INFO',eventScore:Math.round((latest.risk?.score||0)*decay(latest,now))},old,now);return e})}
function hybridClusters(signals,now=Date.now()){const candidates=signals.filter(s=>now-+new Date(s.eventTime||s.timestamp)<=7*24*H&&now>=+new Date(s.eventTime||s.timestamp)&&/sabotage|drone|infrastructure|logistics|rail|port|energy|defence industry|gnss/i.test([s.title,s.kind,s.description].join(' '))),groups=[];for(const seed of candidates){const p=seed.risk?.places?.[0]||seed;const members=candidates.filter(s=>{const q=s.risk?.places?.[0]||s;return Number.isFinite(+p.lat)&&Number.isFinite(+q.lat)&&Math.hypot((p.lat-q.lat)*111,(p.lon-q.lon)*65)<=300});const unique=[...new Map(members.map(s=>[s.eventId||s.id,s])).values()];if(unique.length<3)continue;const categories=new Set(unique.flatMap(s=>String(s.title||s.kind).toLowerCase().match(/infrastructure|logistics|rail|port|energy|drone|gnss|sabotage/g)||[]));if(categories.size<2)continue;const id=unique.map(s=>s.eventId||s.id).sort().join('|');if(groups.some(g=>g.id===id))continue;groups.push({id,title:(p.name||seed.region||'Regional')+' — HYBRID ACTIVITY CLUSTER',count:unique.length,sourceSignals:unique.map(s=>s.signalId||s.id),confidence:new Set(unique.map(s=>s.domain||s.source)).size>=2?'MEDIUM':'LOW',reason:unique.length+' related incidents / 7 days · '+[...categories].join(' + ')+' · geographic and temporal association; common actor not established',cic:cic(unique)})}return groups}
return {signal,decay,ingest,same,canonical,event,status,fingerprint,notification,changes,perimeter,cic,signalEvents,hybridClusters};
});
