(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.NordicWatchRoutes=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
"use strict";
const PATTERNS=Object.freeze({TRANSIT:"TRANSIT",STRAIGHT_TRANSIT:"STRAIGHT TRANSIT",ORBIT:"ORBIT",RACETRACK:"RACETRACK",LOITER:"LOITER",REPEATED_PASS:"REPEATED PASS",HOLDING:"HOLDING / CIRCULAR",HOLDING_PATTERN:"HOLDING PATTERN",BORDER_PARALLEL:"BORDER PARALLEL TRACK",COASTLINE_PARALLEL:"COASTLINE PARALLEL TRACK",HOTSPOT_PROXIMITY:"HOTSPOT PROXIMITY",LONG_DURATION:"LONG DURATION PRESENCE",RETURN_TO_AREA:"RETURN TO AREA",UNKNOWN:"UNKNOWN"});
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function km(a,b){const p1=rad(a.lat),p2=rad(b.lat),dp=p2-p1,dl=rad(b.lon-a.lon),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function bearing(a,b){const dl=rad(b.lon-a.lon),p1=rad(a.lat),p2=rad(b.lat);return (deg(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl)))+360)%360}
const turn=(a,b)=>((b-a+540)%360)-180;
function normalize(points){const out=[];for(const raw of Array.isArray(points)?points:[]){const timestamp=Number(raw.timestamp),lat=Number(raw.lat),lon=Number(raw.lon);if(!Number.isFinite(timestamp)||!Number.isFinite(lat)||!Number.isFinite(lon)||lat< -90||lat>90||lon< -180||lon>180)continue;const point={timestamp,lat,lon,altitude:raw.altitude,speed:Number.isFinite(+raw.speed)?+raw.speed:null,track:Number.isFinite(+raw.track)?+raw.track:null,callsign:String(raw.callsign||"").trim().slice(0,30),hex:String(raw.hex||"").toLowerCase().replace(/[^a-f0-9]/g,"").slice(0,12),classification:String(raw.classification||"UNKNOWN").slice(0,40)};const prev=out.at(-1);if(prev&&point.timestamp<=prev.timestamp){if(point.timestamp===prev.timestamp)out[out.length-1]=point;continue}out.push(point)}return out}
function perpendicular(p,a,b){const x=p.lon,y=p.lat,x1=a.lon,y1=a.lat,x2=b.lon,y2=b.lat,dx=x2-x1,dy=y2-y1;if(!dx&&!dy)return Math.hypot(x-x1,y-y1);const t=clamp(((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy),0,1);return Math.hypot(x-(x1+t*dx),y-(y1+t*dy))}
function simplify(points,tolerance=0.002){if(points.length<=2)return points.slice();let max=0,index=0;for(let i=1;i<points.length-1;i++){const d=perpendicular(points[i],points[0],points.at(-1));if(d>max){max=d;index=i}}if(max<=tolerance)return [points[0],points.at(-1)];const left=simplify(points.slice(0,index+1),tolerance),right=simplify(points.slice(index),tolerance);return left.slice(0,-1).concat(right)}
function metrics(input){const p=normalize(input);if(p.length<2)return {points:p,durationMs:0,distanceKm:0,netKm:0,linearity:0,totalTurn:0,signedTurn:0,reversals:0,aspect:1,radiusKm:0,headingSpread:180};let distanceKm=0,totalTurn=0,signedTurn=0,reversals=0;const bearings=[];for(let i=1;i<p.length;i++){distanceKm+=km(p[i-1],p[i]);bearings.push(bearing(p[i-1],p[i]))}for(let i=1;i<bearings.length;i++){const d=turn(bearings[i-1],bearings[i]);totalTurn+=Math.abs(d);signedTurn+=d;if(Math.abs(d)>120)reversals++}const meanLat=p.reduce((s,x)=>s+x.lat,0)/p.length,meanLon=p.reduce((s,x)=>s+x.lon,0)/p.length;const xs=p.map(x=>(x.lon-meanLon)*Math.cos(rad(meanLat))*111.32),ys=p.map(x=>(x.lat-meanLat)*111.32);const xx=xs.reduce((s,x)=>s+x*x,0)/p.length,yy=ys.reduce((s,y)=>s+y*y,0)/p.length,xy=xs.reduce((s,x,i)=>s+x*ys[i],0)/p.length,tr=xx+yy,disc=Math.sqrt(Math.max(0,(xx-yy)**2+4*xy*xy)),major=Math.sqrt(Math.max(.0001,(tr+disc)/2)),minor=Math.sqrt(Math.max(.0001,(tr-disc)/2)),aspect=major/minor,radiusKm=Math.max(...p.map(x=>km(x,{lat:meanLat,lon:meanLon})));const meanSin=bearings.reduce((s,x)=>s+Math.sin(rad(x)),0)/bearings.length,meanCos=bearings.reduce((s,x)=>s+Math.cos(rad(x)),0)/bearings.length,concentration=Math.hypot(meanSin,meanCos);return {points:p,durationMs:p.at(-1).timestamp-p[0].timestamp,distanceKm,netKm:km(p[0],p.at(-1)),linearity:distanceKm?km(p[0],p.at(-1))/distanceKm:0,totalTurn,signedTurn,reversals,aspect,radiusKm,headingSpread:(1-concentration)*180,center:{lat:meanLat,lon:meanLon}}}
function result(pattern,confidence,m,reason){return {pattern,confidence:Math.round(clamp(confidence,0,100)),reason,metrics:m,evidence:"INFERRED"}}
function detect(points){const m=metrics(points),mins=m.durationMs/60000;if(m.points.length<6||mins<5||m.distanceKm<3)return result(PATTERNS.UNKNOWN,Math.min(35,m.points.length*4),m,"Insufficient track history");const loops=Math.abs(m.signedTurn)/360;
 if(m.aspect>=8&&m.totalTurn>=350&&m.linearity<.48&&mins>=12)return result(PATTERNS.REPEATED_PASS,58+Math.min(30,(m.totalTurn-350)/15)+Math.min(8,m.aspect/2),m,"Repeated traversal of the same elongated area");
 if(m.aspect>=2.2&&m.totalTurn>=500&&m.linearity<.32&&mins>=12)return result(PATTERNS.RACETRACK,55+Math.min(30,(m.totalTurn-500)/12)+Math.min(12,(m.aspect-2.2)*5),m,"Repeated parallel legs and reversing turns");
 if(loops>=1.45&&m.linearity<.3&&m.aspect<2.4)return result(PATTERNS.ORBIT,58+Math.min(32,(loops-1.45)*18)+Math.max(0,10-m.linearity*25),m,"Repeated circular movement around a stable centre");
 if(mins>=20&&m.linearity<.28&&m.radiusKm<=45&&Math.abs(m.signedTurn)/Math.max(1,m.totalTurn)<.45)return result(PATTERNS.LOITER,55+Math.min(25,mins/3)+Math.max(0,15-m.radiusKm/3),m,"Long presence with limited net displacement");
 if(loops>=.65&&m.linearity<.42&&m.aspect<2.2)return result(PATTERNS.HOLDING,52+Math.min(30,loops*16)+Math.max(0,8-m.linearity*15),m,"Circular or holding movement");
 if(m.aspect>=3&&m.totalTurn>=350&&m.linearity<.48&&mins>=12)return result(PATTERNS.REPEATED_PASS,58+Math.min(30,(m.totalTurn-350)/15)+Math.min(8,m.aspect),m,"Repeated traversal of the same elongated area");
 if(mins>=20&&m.linearity<.28&&m.radiusKm<=45)return result(PATTERNS.LOITER,55+Math.min(25,mins/3)+Math.max(0,15-m.radiusKm/3),m,"Long presence with limited net displacement");
 if(m.linearity>=.72&&m.totalTurn<300)return result(PATTERNS.TRANSIT,62+Math.min(30,(m.linearity-.72)*90)+Math.max(0,8-m.totalTurn/40),m,"Predominantly linear movement");
 return result(PATTERNS.UNKNOWN,40+Math.min(25,mins/4),m,"No stable supported pattern");
}
function context(classification,analysis){const role=String(classification?.role||"").toUpperCase(),pattern=analysis.pattern;if(analysis.confidence<55||pattern===PATTERNS.UNKNOWN)return null;let text=null,interest=0;if(role==="AWACS"&&pattern===PATTERNS.RACETRACK)text="Expected airborne surveillance pattern";else if(role==="TANKER"&&pattern===PATTERNS.RACETRACK)text="Possible refuelling orbit";else if(role==="ISR"&&pattern===PATTERNS.REPEATED_PASS){text="Elevated intelligence collection interest";interest=18}else if(role==="FIGHTER"&&pattern===PATTERNS.LOITER){text="Unusual fighter loiter";interest=15}return text?{evidence:"INFERRED",text,interest}:null}
function detectBehavior(points,{hotspots=[],coastlines=[],borders=[],previousVisits=[]}={}){const primary=detect(points),m=primary.metrics,behaviours=[primary.pattern];if(!m.points.length)return {...primary,behaviours};const center=m.center||m.points.at(-1),near=hotspots.find(x=>km(center,{lat:+x.lat,lon:+x.lon})<=Number(x.radiusKm||x.r||100));if(near)behaviours.push(PATTERNS.HOTSPOT_PROXIMITY);if(m.durationMs>=60*60000)behaviours.push(PATTERNS.LONG_DURATION);if(previousVisits.some(x=>km(center,{lat:+x.lat,lon:+x.lon})<=50&&Math.abs(+new Date(x.timestamp)-m.points.at(-1).timestamp)>12*3600000))behaviours.push(PATTERNS.RETURN_TO_AREA);const heading=m.points.length>1?bearing(m.points[0],m.points.at(-1)):null,parallel=(lines,label)=>{if(lines.some(line=>{const pts=line.points||line;if(!Array.isArray(pts)||pts.length<2)return false;const d=Math.min(...m.points.map(p=>Math.min(...pts.map(q=>km(p,{lat:+q[0],lon:+q[1]}))))),lineHeading=bearing({lat:+pts[0][0],lon:+pts[0][1]},{lat:+pts.at(-1)[0],lon:+pts.at(-1)[1]});return d<=80&&Math.abs(turn(heading,lineHeading))<=20}))behaviours.push(label)};parallel(coastlines,PATTERNS.COASTLINE_PARALLEL);parallel(borders,PATTERNS.BORDER_PARALLEL);return {...primary,behaviours:[...new Set(behaviours)],context:{hotspot:near?.name||null},evidence:"INFERRED"}}
return {PATTERNS,normalize,km,bearing,turn,simplify,metrics,detect,detectBehavior,context};
});
