(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.NordicWatchSituations=api})(globalThis,function(){
  'use strict';
  const H=3600000, DAY=24*H;
  const DOMAINS=['NEWS','AVIATION','AIS','GNSS','INFRASTRUCTURE','CYBER','OFFICIAL'];
  const clean=(v,n=500)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,n);
  const norm=v=>clean(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const unique=xs=>[...new Set(xs.filter(Boolean))];
  const clamp=(v,max=100)=>Math.max(0,Math.min(max,Number(v)||0));
  const time=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(+new Date(v))?+new Date(v):null;
  const hash=v=>{let h=2166136261;for(const c of v){h=Math.imul(h^c.charCodeAt(0),16777619)}return (h>>>0).toString(36)};
  function km(a,b){if(a.lat==null||a.lon==null||b.lat==null||b.lon==null)return Infinity;const r=Math.PI/180,q=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lon-a.lon)*r/2)**2;return 12742*Math.asin(Math.min(1,Math.sqrt(q)))}
  function url(v){try{const u=new URL(v);return u.protocol==='https:'?u.href:null}catch{return null}}
  function themes(text){return Object.entries({INFRASTRUCTURE:/infrastructure|infrastruktur/,ENERGY:/power|grid|energy|pipeline|kraft|strom|stromnetz/,RAIL:/rail|railway|logistics|jarnvag|bahn/,TELECOM:/telecom|cable|communications|fiber|telekommun/,CYBER:/cyber|ransomware|malware|ddos/,DRONE:/drone|uav|dron/,GNSS:/gnss|jamming|interference/,MILITARY:/military|naval|airlift|isr|awacs|tanker|fighter|defence|sigint/,LEGAL:/legal|seizure|seized|court|sanction|asset|economic measure/,RHETORIC:/official statement|rhetoric|protest|retaliat|foreign ministry/}).filter(([,re])=>re.test(text)).map(([key])=>key)}
  function normalize(raw){
    if(!raw||typeof raw!=='object')return null;
    const domain=({AIRCRAFT:'AVIATION',MARITIME:'AIS',EVENT:'OFFICIAL',OFFICIAL_STATEMENT:'OFFICIAL'})[raw.domain]||raw.domain;
    const timestamp=time(raw.timestamp??raw.eventTime??raw.lastObservedAt),lat=raw.lat==null?null:Number(raw.lat),lon=raw.lon==null?null:Number(raw.lon);
    if(!DOMAINS.includes(domain)||timestamp===null||!clean(raw.id||raw.signalId)||((lat!==null||lon!==null)&&(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<45||lat>85||lon< -30||lon>50)))return null;
    const title=clean(raw.title||raw.details||raw.kind),text=norm(title+' '+(raw.description||'')+' '+(raw.kind||'')+' '+(raw.capability||'')),sourceUrl=url(raw.sourceUrl||raw.url),source=clean(raw.independenceGroup||raw.source?.publisher||raw.source?.name||raw.source|| (sourceUrl?new URL(sourceUrl).hostname:''),120);
    const evidence=['DIRECT OBSERVATION','CONFIRMED EXTERNAL REPORT','AUTOMATIC ASSESSMENT'].includes(raw.evidence)?raw.evidence:raw.evidence==='CONFIRMED_EXTERNAL'?'CONFIRMED EXTERNAL REPORT':raw.evidence==='OBSERVATION'?'DIRECT OBSERVATION':'AUTOMATIC ASSESSMENT';
    return {id:clean(raw.id||raw.signalId,180),incidentId:clean(raw.incidentId||raw.eventId||raw.id||raw.signalId,180),identity:clean(raw.identity||raw.hex||raw.mmsi,100),domain,timestamp,lat,lon,region:clean(raw.region,100),title,description:clean(raw.description),kind:clean(raw.kind),role:clean(raw.role||raw.capability,80).toUpperCase(),platform:clean(raw.platform,100),entities:unique((Array.isArray(raw.entities)?raw.entities:[]).map(norm)),themes:unique([...(Array.isArray(raw.themes)?raw.themes:[]),...themes(text)]),source:source||'UNKNOWN',sourceUrl,evidence,quality:clamp(raw.quality??50),eventScore:clamp(raw.eventScore),mock:raw.mock===true||raw.source?.quality==='mock',contextOnly:raw.contextOnly===true,confirmedMilitaryEscalation:raw.confirmedMilitaryEscalation===true&&domain==='OFFICIAL'&&evidence==='CONFIRMED EXTERNAL REPORT'&&Boolean(sourceUrl),relation:raw.relation?.confirmed===true&&url(raw.relation.sourceUrl)?{id:clean(raw.relation.id,100),confirmed:true,sourceUrl:url(raw.relation.sourceUrl)}:null};
  }
  // A provider refresh is not an independent occurrence. Aircraft/vessel observations
  // are sampled once per six-hour identity/region slot; dated incidents retain their IDs.
  function occurrence(s){return ['AVIATION','AIS'].includes(s.domain)&&s.identity?`${s.domain}|${s.identity}|${s.region}|${Math.floor(s.timestamp/(6*H))}`:s.incidentId}
  function accumulate(previous,incoming){const map=new Map();for(const raw of [...previous,...incoming]){const s=normalize(raw);if(!s||s.mock||s.contextOnly)continue;const key=occurrence(s),old=map.get(key),track=['AVIATION','AIS'].includes(s.domain)&&s.identity;if(track)s.id='observation-'+hash(key);if(!old||(track?s.timestamp<old.timestamp:s.timestamp>old.timestamp))map.set(key,s)}return [...map.values()].sort((a,b)=>a.timestamp-b.timestamp)}
  function caseOf(members){const text=norm(members.map(s=>s.title+' '+s.description+' '+s.region+' '+s.entities.join(' ')).join(' '));
    if(/svalbard|barentsburg|professor molchanov/.test(text)&&members.some(s=>s.themes.includes('LEGAL'))&&members.some(s=>s.themes.includes('RHETORIC')))return {id:'SVALBARD_ASSETS',title:'Svalbard / Barentsburg · state-asset measures and official response'};
    if(/jan mayen|barents|high north/.test(text)&&/airlift|c17|c-17|a400/.test(text)&&/container|mobile|forward bas|typhon|long.range|sea denial|logistics|navwarn|notam|restriction/.test(text))return {id:'HIGH_NORTH_FIRES',title:'High North · distributed basing / sea-denial indicators'};
    return null;
  }
  function pair(a,b){const distanceKm=km(a,b),hours=Math.abs(a.timestamp-b.timestamp)/H,sharedThemes=a.themes.filter(t=>b.themes.includes(t)),sharedEntities=a.entities.filter(e=>b.entities.includes(e));
    const infrastructure=a.themes.some(t=>['INFRASTRUCTURE','ENERGY','RAIL','TELECOM','CYBER','DRONE','GNSS'].includes(t))&&b.themes.some(t=>['INFRASTRUCTURE','ENERGY','RAIL','TELECOM','CYBER','DRONE','GNSS'].includes(t));
    const air=a.domain==='AVIATION'&&b.domain==='AVIATION',regionalCase=caseOf([a,b]);
    const near=distanceKm<=250||(distanceKm===Infinity&&a.region&&a.region===b.region);
    const related=hours<=7*24&&((near&&(sharedThemes.length||sharedEntities.length||infrastructure||a.domain!==b.domain))||(regionalCase&&distanceKm<=1200));
    return {related:Boolean(related),a:a.id,b:b.id,distanceKm:Number.isFinite(distanceKm)?Math.round(distanceKm):null,hours:Math.round(hours*10)/10,reason:regionalCase?regionalCase.title:air?'Regional surveillance recurrence / complementary aircraft roles':infrastructure?'Shared infrastructure function and regional proximity':sharedThemes.length?'Shared themes: '+sharedThemes.join(', '):sharedEntities.length?'Shared named entities':'Cross-domain temporal and geographic proximity'};
  }
  function cic(members,links){const days=unique(members.map(s=>Math.floor(s.timestamp/DAY))).length,slots=unique(members.map(s=>Math.floor(s.timestamp/(6*H)))).length,domains=unique(members.map(s=>s.domain)),sources=unique(members.map(s=>s.source).filter(s=>s!=='UNKNOWN'));
    const coherence=Math.min(1,(days*.5+slots*.25)/3),interaction=Math.min(1,(links.filter(p=>p.hours<=6).length/Math.max(1,members.length-1))*.6+domains.length*.15),corroboration=Math.min(1,sources.length/3)*Math.min(1,domains.length/2+.5);
    return {coherence,interaction,corroboration,score:Math.round(100*coherence*interaction*corroboration),independentSources:sources.length,dimensions:domains.length,observedDays:days};
  }
  function assess(members,history,now){const links=[];for(let i=0;i<members.length;i++)for(let j=i+1;j<members.length;j++){const p=pair(members[i],members[j]);if(p.related)links.push(p)}
    const anchor=members[0],reference=history.filter(s=>s.timestamp<now-7*DAY&&s.timestamp>=now-30*DAY&&pair({...anchor,timestamp:s.timestamp},s).related),baselineDays=unique(reference.map(s=>Math.floor(s.timestamp/DAY))).length,expectedPerDay=baselineDays>=3?reference.length/baselineDays:null;
    const recent=members.filter(s=>s.timestamp>=now-6*H).length,prior=members.filter(s=>s.timestamp>=now-12*H&&s.timestamp<now-6*H).length,currentDay=members.filter(s=>s.timestamp>now-DAY).length;
    const acceleration=recent>=3?clamp((recent-prior)*20):0,deviation=expectedPerDay===null?0:clamp((currentDay-expectedPerDay)/Math.max(1,expectedPerDay)*50),c=cic(members,links),airOnly=members.every(s=>s.domain==='AVIATION');
    const components={accumulation:Math.min(30,members.length*6),temporalCompression:Math.min(15,recent*3),sourceSupport:Math.min(15,c.independentSources*5),cic:c.score*.15,baselineDeviation:deviation*.1,acceleration:acceleration*.12,eventContext:Math.max(...members.map(s=>s.eventScore))*.03};
    let score=Math.round(clamp(Object.values(components).reduce((a,b)=>a+b,0)));
    if(members.length===1)score=Math.min(25,score);if(c.independentSources<2)score=Math.min(49,score);
    const roles=unique(members.map(s=>s.role)),surveillanceOnly=airOnly&&roles.every(r=>['ISR','SIGINT','ASW','MARITIME_PATROL'].includes(r));if(surveillanceOnly)score=Math.min(expectedPerDay!==null&&deviation===0?30:54,score);
    const level=score>=80?'HIGH':score>=65?'ELEVATED':score>=45?'DEVELOPING':'WATCH',relationship=members.length>1&&members.every(s=>s.relation?.confirmed&&s.relation.id&&s.relation.id===members[0].relation?.id)?'CONFIRMED RELATIONSHIP':links.some(p=>p.hours<=6)?'OBSERVED CORRELATION':'POSSIBLE RELATIONSHIP';
    const special=caseOf(members),airPackage=roles.filter(r=>['ISR','SIGINT','AWACS','AEW&C','EW','TANKER','FIGHTER'].includes(r)).length>=3;
    const has=t=>members.some(s=>s.themes.includes(t)),militaryLayers=unique(members.filter(s=>['AVIATION','AIS','GNSS'].includes(s.domain)).map(s=>s.domain)),confirmedMilitaryEscalation=members.some(s=>s.confirmedMilitaryEscalation);
    const escalation={legalEconomic:has('LEGAL'),diplomatic:members.some(s=>/diplomatic|formal protest|countermeasure|ambassador/.test(norm(s.title+' '+s.description))),informationPolitical:has('RHETORIC'),militarySignalling:militaryLayers.length>=2,militarySignallingScore:militaryLayers.length<2?Math.min(25,militaryLayers.length*15):Math.min(75,militaryLayers.length*15+deviation*.2),confirmedMilitaryEscalation};
    const summary=surveillanceOnly?(deviation>0?'Elevated surveillance':'Recurring surveillance')+' · baseline/deviation signal; no escalation inferred.':special?.id==='SVALBARD_ASSETS'?'Political and legal tension around Svalbard shows cross-domain correlation. '+(confirmedMilitaryEscalation?'A source explicitly confirms military escalation; inspect its evidence.':'No military escalation is confirmed.'):special?.id==='HIGH_NORTH_FIRES'?'Regional activity has characteristics consistent with temporary distributed basing or sea-denial preparation. The exact capability is not confirmed.':members.length>=3?'Something is developing here. Multiple anomalies occur within a compressed regional window. No common cause is confirmed.':'Limited regional evidence; continue monitoring.';
    return {situationScore:score,level,confidence:c.independentSources>=3&&members.every(s=>s.quality>=65)?'HIGH':c.independentSources>=2?'MEDIUM':'LOW',relationship,summary,components,cic:c,baseline:{sampleDays:baselineDays,expectedPerDay,deviation,status:expectedPerDay===null?'INSUFFICIENT DATA':deviation>25?'ABOVE BASELINE':'WITHIN BASELINE'},acceleration:{recent6h:recent,previous6h:prior,score:acceleration},links,airPackage,surveillanceOnly,case:special,escalation};
  }
  function build(input,{now=Date.now(),previous=[]}={}){const history=accumulate([],input).filter(s=>s.timestamp<=now),active=history.filter(s=>s.timestamp>=now-7*DAY),groups=[];
    for(const seed of active){if(groups.some(g=>g.some(s=>s.id===seed.id)))continue;const members=[seed];for(const candidate of active){if(candidate.id===seed.id||groups.some(g=>g.some(s=>s.id===candidate.id)))continue;if(pair(seed,candidate).related)members.push(candidate)}groups.push(members)}
    const used=new Set();return groups.map(members=>{const a=assess(members,history,now),old=previous.filter(p=>!used.has(p.situationId)).map(p=>({p,overlap:p.signalIds.filter(id=>members.some(s=>s.id===id)).length})).sort((x,y)=>y.overlap-x.overlap)[0],situationId=old?.overlap?old.p.situationId:'situation-'+hash(members[0].id);used.add(situationId);
      return {...a,situationId,title:a.case?.title||(members[0].region||'Regional')+' · '+(a.surveillanceOnly?'surveillance':a.airPackage?'air package':'developing situation'),signalIds:members.map(s=>s.id).sort(),observations:members,firstObservedAt:old?.overlap?old.p.firstObservedAt:members[0].timestamp,lastObservedAt:Math.max(...members.map(s=>s.timestamp)),lat:members.find(s=>s.lat!==null)?.lat??null,lon:members.find(s=>s.lon!==null)?.lon??null,domains:unique(members.map(s=>s.domain)).sort(),status:'ACTIVE'};
    }).sort((a,b)=>b.situationScore-a.situationScore);
  }
  function alert(s,old){const levels=['WATCH','DEVELOPING','ELEVATED','HIGH'],newSignals=!old||s.signalIds.some(id=>!old.signalIds.includes(id)),material=!old||levels.indexOf(s.level)>levels.indexOf(old.level)||s.relationship==='CONFIRMED RELATIONSHIP'&&old.relationship!==s.relationship||newSignals&&s.situationScore>=(old.situationScore||0)+10;
    return {shouldNotify:s.situationScore>=65&&s.observations.length>=3&&s.cic.independentSources>=2&&material,fingerprint:hash(JSON.stringify([s.level,s.relationship,s.signalIds])),record:{signalIds:s.signalIds,level:s.level,relationship:s.relationship,situationScore:s.situationScore}};
  }
  function importSignals(rows){if(!Array.isArray(rows)||rows.length>10000)throw new Error('Expected an array with at most 10,000 observations');const accepted=[],rejected=[];rows.forEach((raw,i)=>{const s=normalize(raw);if(!s||s.source==='UNKNOWN')rejected.push(i);else accepted.push(s)});return {accepted,rejected}}
  // Approximate regional geocoding for upstream reports which did not qualify as
  // high-scoring military events. These weak reports still reach SituationScore.
  function fromArticle(a){const text=norm([a.title,a.description,a.summary].join(' ')),regions=[[/svalbard|barentsburg|professor molchanov/,'Svalbard / Barentsburg',78.06,14.22],[/jan mayen/,'Jan Mayen / High North',70.98,-8.46],[/murmansk|kola|barents/,'Kola / Barents',69,33],[/kiel|rostock|schleswig|mecklenburg|northern germany|hamburg/,'Northern Germany',54.1,12],[/kaliningrad|konigsberg|baltijsk/,'Kaliningrad / Baltijsk',54.7,20.5],[/baltic|gotland/,'Baltic Sea',57.5,19],[/norway|norwegian|high north/,'Northern Norway',69,20]],region=regions.find(([re])=>re.test(text));if(!region||!themes(text).length)return null;const sourceUrl=url(a.url||a.sourceUrl);return normalize({id:a.signalId||a.id,incidentId:a.eventId||a.signalId||a.id,domain:'NEWS',timestamp:a.temporal?.containsNewDevelopment?a.lastUpdatedAt:a.eventTime||a.publishedAt||a.ingestedAt,lat:region[2],lon:region[3],region:region[1],title:a.title,description:a.description||a.summary,source:sourceUrl?new URL(sourceUrl).hostname:a.sourceName,sourceUrl,evidence:'DIRECT OBSERVATION',quality:a.timeStatus==='TIME_UNCERTAIN'?35:65,eventScore:a.risk?.score||20})}
  return {DOMAINS,normalize,accumulate,build,assess,alert,cic,pair,km,importSignals,fromArticle};
});
