import assert from "node:assert/strict";
import fixture from "../mock/external-military-reports.json" with {type:"json"};
import {sourceTrust,extractMilitaryEntities,classifyEvent,geolocate,normalizeReport,importReports,correlate,toEvent} from "../external-report-core.mjs";

for(const [text,type,role] of [["Il-20 SIGINT","IL-20","ISR"],["Il-22 EW","IL-22","EW"],["Il-38 patrol","IL-38","ASW"],["Tu-142","TU-142","ASW"],["Tu-95","TU-95","BOMBER"],["Tu-160","TU-160","BOMBER"],["Su-24","SU-24","FIGHTER"],["Su-27","SU-27","FIGHTER"],["Su-30","SU-30","FIGHTER"],["Su-35","SU-35","FIGHTER"],["MiG-29","MIG-29","FIGHTER"],["MiG-31","MIG-31","FIGHTER"],["RC-135","RC-135","ISR"],["P-8","P-8","ASW"],["E-3","E-3","AWACS"],["E-7","E-7","AWACS"],["GlobalEye","GlobalEye","AWACS"],["EA-37B","EA-37B","EW"],["KC-135","KC-135","TANKER"],["KC-46","KC-46","TANKER"],["A330 MRTT","A330 MRTT","TANKER"],["Gripen","Gripen","FIGHTER"],["F-16","F-16","FIGHTER"],["F-18","F-18","FIGHTER"],["F-35","F-35","FIGHTER"],["Rafale","Rafale","FIGHTER"],["Typhoon","Typhoon","FIGHTER"]]){const p=extractMilitaryEntities(text).primary;assert.equal(p.aircraftType,type);assert.equal(p.aircraftRole,role)}
assert.equal(classifyEvent("fighters intercepted reconnaissance aircraft"),"intercept");
const geo=geolocate("approximately 30 km north of Łeba over the Baltic Sea");assert(geo);assert.equal(geo.locationConfidence,"APPROXIMATE");assert.equal(geo.locationText,"30 km north of Łeba");assert(Math.abs(geo.latitude-55.0304)<.02);
const report=normalizeReport(fixture.reports[0]);assert(report);assert.equal(report.evidenceType,"CONFIRMED_EXTERNAL");assert.equal(report.aircraftType,"IL-20");assert.equal(report.aircraftRole,"ISR");assert.deepEqual(report.aircraftCapabilities,["SIGINT","ELINT"]);assert.equal(report.eventType,"intercept");assert.equal(report.trackObserved,false);assert.equal(report.locationConfidence,"APPROXIMATE");assert.equal(report.interestScore,100);assert.equal(sourceTrust("https://x.com/example/status/1"),null);
const low=normalizeReport({...fixture.reports[0],id:"low",sourceUrl:"https://www.navalnews.com/naval-news/2026/08/example/"});assert.equal(low.evidenceType,"INFERRED","defence publication alone must remain a candidate");
const duplicate={...fixture.reports[0],id:"other-article",sourceUrl:"https://www.polskieradio.pl/395/7784/Artykul/1"};const imported=importReports([fixture.reports[0],duplicate]);assert.equal(imported.reports.length,1);assert.equal(imported.reports[0].sources.length,2);
const noTrack=correlate(report,[],[],60);assert.equal(noTrack.trackObserved,false);assert.equal(noTrack.observed.length,0);
const staleLive=correlate(report,[{lat:55.03,lon:17.56,role:"FIGHTER"}],[],60,Date.parse("2026-09-03T10:00:00Z"));assert.equal(staleLive.observed.length,0,"current traffic outside the ±60 minute window must not correlate");
const timelyLive=correlate(report,[{lat:55.03,lon:17.56,role:"FIGHTER",timestamp:+new Date(report.timestamp)+10*60000}],[],60,Date.parse("2026-09-03T10:00:00Z"));assert.equal(timelyLive.observed.length,1);
const historical=[{t:+new Date(report.timestamp)+30*60000,cats:{fighter:2,awacs:1}}],correlated=correlate(report,[],historical,60);assert(correlated.signals.some(x=>/possible response, not a confirmed intercept/i.test(x)));assert(correlated.signals.some(x=>/AWACS/i.test(x)));
const event=toEvent(report,correlated);assert.equal(event.confidence,"CONFIRMED_EXTERNAL");assert.equal(event.externalReport.trackObserved,false);assert(event.discovery.score>=report.interestScore);assert(event.evidence.inferred.every(x=>x.text));
console.log("external military report tests passed");
