const {test}=require('node:test');
const assert=require('node:assert/strict');
const I=require('../intelligence-core.js'),S=require('../situational-engine.js');
const now=Date.parse('2026-09-05T12:00:00Z'),H=3600000;
const article=(hours=0,extra={})=>({title:'Baltic port infrastructure sabotage',url:'https://example.org/story',publishedAt:new Date(now-hours*H).toISOString(),...extra});
test('freshness and all news decay boundaries',()=>{for(const [h,f,d] of [[0,'FRESH',1],[12,'FRESH',.75],[24,'RECENT',.4],[48,'RECENT',.15],[72,'RECENT',.15],[120,'HISTORICAL',0]]){const s=I.signal(article(h),now);assert.equal(s.freshness,f);assert.equal(I.decay(s,now),d)}});
test('republished old occurrence is historical',()=>{const s=I.signal(article(0,{eventTime:new Date(now-120*H).toISOString()}),now);assert.equal(s.freshness,'HISTORICAL');assert.equal(I.decay(s,now),0)});
test('canonical URL, cross-feed headline and re-ingestion never renew age',()=>{let rows=I.ingest([], [article(120)],now);rows=I.ingest(rows,[article(0,{url:'https://example.org/story?utm_source=feed'}),article(0,{url:'https://other.org/story'})],now);assert.equal(rows.length,1);assert.equal(rows[0].freshness,'HISTORICAL')});
test('unknown timestamp expires within 24 hours across restart',()=>{let rows=I.ingest([],[article(0,{publishedAt:null})],now);assert.equal(rows[0].timeStatus,'TIME_UNCERTAIN');assert(rows[0].confidence<=40);rows=I.ingest(JSON.parse(JSON.stringify(rows)),[article(0,{publishedAt:null})],now+25*H);assert.equal(rows[0].freshness,'RECENT');assert(+new Date(rows[0].expiresAt)<=now+24*H)});
const base={id:'namejs-2026',title:'NAMEJS 2026',eventType:'military_exercise',startTime:'2026-09-01',endTime:'2026-10-01',countries:['Latvia'],areaName:'Latvia',severity:'INFO',confidence:'CONFIRMED'};
test('ordinary event expires, fresh observation reactivates, exercise persists',()=>{const old=I.event({...base,eventType:'drone_incident'},null,now);assert.equal(old.status,'INACTIVE');assert.equal(I.event({...old,lastObservedAt:new Date(now).toISOString()},old,now).status,'ACTIVE');assert.equal(I.event(base,null,now).status,'ACTIVE')});
test('NAMEJS stable for days, reload, PWA restart and SW update',()=>{const e=I.event(base,null,now),first=I.notification(e,null,now);assert(first.shouldNotify);for(let d=0;d<5;d++){const ledger=JSON.parse(JSON.stringify(first.record));assert.equal(I.notification(I.event(base,null,now+d*24*H),ledger,now+d*24*H).shouldNotify,false)}});
test('material updates notify, order and poll time do not',()=>{const e=I.event(base,null,now),p=I.notification(e).record;assert(I.notification({...e,severity:'HIGH'},p).shouldNotify);assert(I.notification({...e,locations:['Latvia','Estonia']},p).shouldNotify);assert.equal(I.notification({...e,lastObservedAt:new Date(now+H).toISOString()},p).shouldNotify,false);assert.equal(I.changes([e],[e]).length,0);assert.equal(I.changes([e],[{...e,severity:'HIGH'}])[0].kind,'ESCALATED')});
test('several signals link to one persistent event',()=>{const signals=[I.signal(article(20,{eventId:'event-one',signalId:'a'}),now),I.signal(article(0,{eventId:'event-one',signalId:'b',url:'https://second.org/new'}),now)];const events=I.signalEvents(signals,[],now);assert.equal(events.length,1);assert.equal(events[0].sourceSignals.length,2);assert.equal(events[0].lastObservedAt,new Date(now).toISOString())});
test('Silver Wotan articles and observations fuse into one materially enriched event',()=>{const base={operationId:'silver-wotan-2026',operationName:'Silver Wotan 2026',eventType:'military_exercise',eventTime:new Date(now-H).toISOString(),publishedAt:new Date(now-H).toISOString(),risk:{score:60,confidence:'HIGH',severity:'INFO',places:[{name:'Gotland'}]}},signals=[
 I.signal({...base,signalId:'official-sweden',title:'German reinforcement operation on Gotland',url:'https://forsvarsmakten.se/silver',domain:'OFFICIAL',components:['Visby harbour','Swedish coastal missile unit'],relationships:[{subject:'German naval units',predicate:'PROTECT',object:'reinforcement transport'}]},now),
 I.signal({...base,signalId:'official-germany',title:'Exercise Silver Wotan',url:'https://bundeswehr.de/silver',domain:'OFFICIAL',components:['German ground force','German fighters'],relationships:[{subject:'reinforcement transport',predicate:'DELIVERS',object:'coastal missile unit'}]},now),
 I.signal({...base,signalId:'adsb',title:'Military air observation',url:'https://example.org/adsb',domain:'AVIATION',components:['Swedish/German fighters']},now)
 ];const first=I.signalEvents(signals,[],now);assert.equal(first.length,1);assert.equal(first[0].sourceSignals.length,3);assert.equal(first[0].sourceCount,3);assert.equal(first[0].relationships.length,2);const enriched=I.signalEvents([...signals,I.signal({...base,signalId:'ais',title:'Naval protection observed',url:'https://example.org/ais',domain:'AIS',components:['Swedish corvette']},now)],first,now);assert.equal(enriched.length,1);assert.equal(enriched[0].materiallyUpdated,true);assert(enriched[0].components.includes('Swedish corvette'))});
test('Gerbera intent preserves unknown, official assessment and later confirmation',()=>{const base={eventId:'gerbera-lithuania',title:'Gerbera over Lithuania',eventTime:new Date(now-H).toISOString(),publishedAt:new Date(now-H).toISOString(),risk:{score:70,confidence:'HIGH'},url:'https://example.org/gerbera'},first=I.signalEvents([I.signal({...base,claims:[{field:'intent',value:'UNKNOWN',level:'UNKNOWN'}]},now)],[],now),second=I.signalEvents([I.signal({...base,url:'https://official.example/assessment',containsNewDevelopment:true,lastUpdatedAt:new Date(now).toISOString(),claims:[{field:'intent',value:'probable diversion after EW',level:'OFFICIAL_ASSESSMENT'}]},now)],first,now),third=I.signalEvents([I.signal({...base,url:'https://lab.example/confirmation',containsNewDevelopment:true,lastUpdatedAt:new Date(now+H).toISOString(),claims:[{field:'intent',value:'diverted by EW',level:'CONFIRMED'}]},now+H)],second,now+H);assert.equal(third.length,1);assert.equal(third[0].claimHistory.length,3);assert.equal(third[0].currentClaims.intent.level,'CONFIRMED');assert(third[0].claimHistory.some(c=>c.level==='UNKNOWN'));assert(third[0].claimHistory.some(c=>c.level==='OFFICIAL_ASSESSMENT'))});
test('external upstream trigger creates watch directives, never AOI incidents',()=>{const triggers=[{id:'mass-strike',title:'Mass drone strike in Russia',timestamp:new Date(now-H).toISOString(),watchAreas:['Kaliningrad / Baltijsk','Kola'],watchTargets:['GNSS','EW','AEW','ISR','FIGHTER_CAP']}],watch=I.watchDirectives(triggers,now);assert.equal(watch.length,1);assert.equal(watch[0].scope,'EXTERNAL_TRIGGER');assert.equal(watch[0].directAoiEvent,false);assert(watch[0].watchTargets.includes('GNSS'))});
test('security perimeter gates inland incidents',()=>{assert.equal(I.perimeter({title:'German local crime'}).visible,false);assert.equal(I.perimeter({title:'Rostock port sabotage'}).tier,'BALTIC FLANK');assert.equal(I.perimeter({title:'German rail sabotage affecting Baltic logistics'}).visible,true)});
test('hybrid cluster needs distinct incidents and multiple categories',()=>{const rows=['port sabotage','rail logistics incident','energy infrastructure drone'].map((title,i)=>({...I.signal(article(i*24,{title,url:'https://example.org/'+i}),now),eventId:'e'+i,lat:54+i*.1,lon:12,domain:i===0?'official':'media'}));assert.equal(I.hybridClusters(rows,now)[0].count,3);assert.equal(I.hybridClusters([rows[0],rows[0],rows[0]],now).length,0)});
test('recurring ISR is recurrence, ISR AWACS tanker forms air package',()=>{const rows=['ISR','AWACS','TANKER'].map((capability,i)=>({id:'a'+i,domain:'AIRCRAFT',evidence:'OBSERVATION',timestamp:new Date(now).toISOString(),lat:55,lon:20,capability,quality:85}));assert.equal(S.correlate(rows,{now}).length,1);assert.match(S.correlate(rows,{now})[0].correlationReason,/Air package/);const recurrence=S.recurrence([0,1,2].map(d=>({identity:'ARTEMIS II',region:'Baltic',timestamp:new Date(now-d*24*H).toISOString()})),{now});assert.equal(recurrence[0].daysObserved,3)});
