const {chromium,devices}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!p.startsWith(root+path.sep)&&p!==root){res.writeHead(403).end();return}const file=p===root?path.join(root,'index.html'):p;try{res.setHeader('Content-Type',file.endsWith('.html')?'text/html':/\.m?js$/.test(file)?'application/javascript':file.endsWith('.css')?'text/css':'application/json');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const profile of [{name:'desktop',viewport:{width:1440,height:1000}},{name:'Android',...devices['Pixel 7']}]){const {name,...options}=profile,ctx=await browser.newContext({...options,serviceWorkers:'block'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const now=Date.now(),publishedAt=new Date(now-40*3600000).toISOString();const seed=JSON.parse(fs.readFileSync(path.join(root,'mock/events.json'))).events[0];const event={...seed,seed:false,startTime:publishedAt,updatedAt:publishedAt,lastObservedAt:publishedAt};const globalEvent={...event,id:'egypt',title:'Egypt International Airshow 2026',description:'US military aircraft at Egypt airshow',areaName:'Egypt',countries:['Egypt'],latitude:30,longitude:31,sourceUrl:'https://www.dvidshub.net/news/egypt'};
await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin===origin)return r.continue();if(u.hostname==='unpkg.com')return r.continue();if(u.pathname.endsWith('/events'))return r.fulfill({json:{events:[event,globalEvent]}});if(u.pathname.endsWith('/news')||u.hostname==='api.gdeltproject.org')return r.fulfill({json:{articles:[{title:'NAMEJS 2026',url:event.sourceUrl,publishedAt,description:event.description},{title:globalEvent.title,url:globalEvent.sourceUrl,publishedAt}],available:2,total:2,degraded:false}});return r.fulfill({json:{ac:[],aircraft:[],articles:[]}})});
await page.goto(origin+'/?debugNews=1');await page.waitForFunction(()=>window.nordicWatchNewsDiagnostics?.counters?.dailyBriefEvaluated>0);await page.evaluate(()=>changedBtn.onclick());assert(!(await page.locator('#changes').innerText()).includes('Egypt'));assert((await page.locator('#changes').innerText()).includes('NAMEJS'));await page.evaluate(()=>drawerEl.classList.remove('show'));
for(const kind of ['morning','evening']){await page.evaluate(kind=>generateBrief(kind),kind);const body=await page.locator('#briefContent').innerText();assert.match(body,/Relevant stored news evaluated: [1-9]/);assert(!body.includes('Egypt International'));const box=await page.locator('#briefClose').boundingBox();assert(box&&box.y>=0&&box.y+box.height<=options.viewport.height,'close button visible');await page.locator('#briefClose').click();assert(!(await page.locator('#briefDrawer').getAttribute('class')).includes('show'))}
assert.deepEqual(errors,[]);console.log(name+': What Changed + Morning/Evening routing, count and close passed');await ctx.close()}}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});

