const {test}=require('node:test'),assert=require('node:assert/strict');const R=require('../news-routing.js'),B=require('../brief-engine.js');
const now=Date.parse('2026-09-07T10:00:00Z'),H=3600000;
const report=(title,more={})=>({title,publishedAt:new Date(now-40*H).toISOString(),url:'https://www.nato.int/report',...more});
test('NAMEJS official report routes to both consumers with external evidence',()=>{const routed=R.route([report('NAMEJS 2026')],{now});assert.equal(routed.articles.length,1);assert.equal(routed.events[0].eventType,'MILITARY_EXERCISE');assert.equal(routed.events[0].evidenceType,'CONFIRMED_EXTERNAL');assert(routed.events[0].relevance.matchedRegions.includes('Latvia'));const brief=B.build({articles:routed.articles,now});assert.equal(brief.relevantStoredNewsEvaluated,1);assert.equal(brief.developments[0].evidence,'CONFIRMED EXTERNAL REPORT');assert(routed.diagnostics[0].includedInWhatChanged)});
for(const title of ['The U.S. Arrives to Showcase Unparalleled Defense at Egypt International Airshow 2026','Exercise Phoenix Express 2026 in Tunisia','Super Garuda Shield 26','Freedom Edge 2026'])test('exclude global control: '+title,()=>{const r=R.route([report(title)],{now});assert.equal(r.articles.length,0);assert.equal(r.events.length,0);assert.match(r.diagnostics[0].exclusionReason,/No explicit/)});
test('deployment destination qualifies while NATO identity alone does not',()=>{assert(R.evaluateNordicRelevance(report('US troops depart Texas',{destination:'Latvia',description:'Military deployment'})).relevant);assert(!R.evaluateNordicRelevance(report('NATO delegation attends Egypt airshow')).relevant)});
test('Nordic company or participant mentions do not relocate foreign events into the AOI',()=>{
 const bangladesh=report('MAURIC to Design Riverine Patrol Vessels for the Bangladesh Coast Guards',{description:'A Norwegian company was selected for a commercial naval design project in South Asia.'});
 const ramstein=report('LRMC and Ramstein Host Danish Flyver Ruck March',{description:'A Danish Air Force ceremonial ruck march took place at Landstuhl in Kaiserslautern.'});
 for(const item of [bangladesh,ramstein]){const result=R.route([item],{now});assert.equal(result.articles.length,0);assert.match(result.diagnostics[0].exclusionReason,/outside the AOI/)}
});
test('four NAMEJS articles form one event with four sources and stable lifecycle',()=>{const rows=Array.from({length:4},(_,i)=>report('NAMEJS 2026 report '+i,{id:'a'+i,url:'https://source'+i+'.example/report'}));const first=R.route(rows,{now});assert.equal(first.events.length,1);assert.equal(first.events[0].sourceCount,4);const repeat=R.route(rows,{now:now+H,previous:first.events});assert.equal(repeat.events[0].lifecycle,'developing');assert.equal(repeat.counters.whatChanged,0);assert.equal(repeat.counters.dailyBriefEvaluated,1);const revised=R.route([...rows,report('NAMEJS 2026 new deployment',{url:'https://new.example/report',lastUpdatedAt:new Date(now+H).toISOString()})],{now:now+H,previous:repeat.events});assert.equal(revised.events[0].lifecycle,'updated');assert.equal(revised.events[0].firstSeen,now)});
test('relevance failure is closed and reduces brief confidence',()=>{const routed=R.route([report('NAMEJS 2026'),report('Egypt airshow')],{now,evaluate:()=>{throw Error('broken geo stage')}});assert(routed.degraded);assert.equal(routed.events.length,0);assert(routed.diagnostics.every(d=>d.exclusionReason==='Relevance processing degraded'));assert.equal(B.build({articles:routed.articles,now}).coverageStatus,'INSUFFICIENT')});
test('ongoing seven day context is retained without using polls to renew evidence',()=>{const r=R.route([report('NAMEJS 2026',{ongoing:true,publishedAt:new Date(now-100*H).toISOString(),lastChecked:new Date(now).toISOString()})],{now});assert.equal(r.events.length,1);assert.equal(r.articles.length,0);assert.match(r.diagnostics[0].exclusionReason,/lastChecked/)});
test('official event and same URL article share one normalized event',()=>{const r=R.route([report('Latvia military exercise',{id:'article'}),report('Latvia military exercise',{id:'event',eventType:'military_exercise',sourceUrl:'https://www.nato.int/report'})],{now});assert.equal(r.events.length,1);assert.equal(r.articles.length,1)});
test('worker routing metadata does not refresh a stale report on re-ingestion',()=>{const first=R.route([report('NAMEJS 2026')],{now});const later=R.route(first.articles,{now:now+50*H});assert.equal(later.articles.length,0)});
test('explicit source signal associations connect distinct report titles',()=>{const r=R.route([report('Baltic Il-20 interception',{signalId:'s1',eventId:'one'}),report('Polish fighters over Baltic Sea',{signalId:'s2',eventId:'two',url:'https://other.example/story'}),report('Baltic intercept event',{eventId:'intercept',sourceSignals:['s1','s2'],url:'https://third.example/story'})],{now});assert.equal(r.events.length,1);assert.equal(r.events[0].sourceCount,3)});
