const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),A=require("../aircraft-classifier.js"),S=require("../special-mission-analysis.js"),R=require("../route-pattern.js");
const classify=x=>A.classifyAircraft(x),start=Date.parse("2026-09-03T08:00:00Z");
const rc={hex:"ae01aa",t:"R135",operator:"United States Air Force",lat:70.25,lon:29.5,military:true};
const result=classify(rc);assert.equal(result.base,"MILITARY");assert.equal(result.role,"ISR");assert.equal(result.subrole,"SIGINT / ELINT");assert.equal(result.interestClass,"HIGH_VALUE_ISR");assert.notEqual(result.role,"OTHER");
const passes=[];for(let lap=0;lap<4;lap++){const reverse=lap%2===1;for(let i=0;i<10;i++){const x=reverse?9-i:i;passes.push({timestamp:start+passes.length*60000,lat:70.1+(lap%2)*.004,lon:27+x*.035,speed:380,hex:rc.hex})}}
const pattern=R.detect(passes);assert(["REPEATED PASS","RACETRACK"].includes(pattern.pattern));
const fighter={hex:"f1",t:"F35",military:true,lat:70.1,lon:28.5},tanker={hex:"t1",t:"KC135",military:true,lat:69.8,lon:26.5},awacs={hex:"a1",t:"E3A",military:true,lat:69.7,lon:27};
const assessment=S.assess(rc,[rc,fighter,tanker,awacs],classify,pattern,{firstAppearance:true});assert.equal(assessment.level,"HIGH");assert.equal(assessment.eligible,true);assert(assessment.score>=85);assert(assessment.strategic.name.includes("Kola")||assessment.strategic.name.includes("Finnmark"));assert(assessment.nearbyRoles.includes("FIGHTER"));assert.equal(assessment.evidence.observed,"OBSERVED");assert.equal(assessment.evidence.assessment,"INFERRED");assert.match(assessment.inference,/Possible supported ISR mission/);
const borderTrack=R.detect(Array.from({length:41},(_,i)=>({timestamp:start+i*60000,lat:68.2+i*.04,lon:28+i*.05,hex:rc.hex}))),borderAssessment=S.assess(rc,[rc],classify,borderTrack);assert.equal(borderTrack.pattern,"TRANSIT");assert.equal(borderAssessment.pattern,"BORDER PARALLEL TRACK");
const central={...rc,lat:59.3,lon:18.1},transit=R.detect(Array.from({length:31},(_,i)=>({timestamp:start+i*60000,lat:58+i*.035,lon:17+i*.025,hex:rc.hex}))),ordinary=S.assess(central,[central],classify,transit);assert.equal(ordinary.eligible,false);assert(ordinary.score<58,"ordinary transit outside a strategic area should not create a high alert");
assert.equal(S.rarity([],"RC-135",start),null);const history=Array.from({length:9},(_,i)=>({t:start-(8-i)*6*3600000,specialPlatforms:[]}));assert.match(S.rarity(history,"RC-135",start).claim,/not present/);
const ui=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8"),core=fs.readFileSync(path.join(__dirname,"..","special-mission-analysis.js"),"utf8"),sw=fs.readFileSync(path.join(__dirname,"..","sw.js"),"utf8");for(const text of ["CONFIRMED BY LIVE AIRCRAFT DATA","Strategic context:","Interest:","DIRECT OBSERVATION","NORDICWATCH_SPECIAL_MISSION_SEEN"])assert(ui.includes(text),`UI must retain ${text}`);assert(core.includes("Possible supported ISR mission"));assert(sw.includes("special-mission-analysis.js"));assert(ui.includes("v1.1"));
console.log("special mission analysis tests passed");
