"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const root=path.join(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const sw=fs.readFileSync(path.join(root,"sw.js"),"utf8");
const seed=JSON.parse(fs.readFileSync(path.join(root,"mock","uav-incidents.json"),"utf8"));
assert.match(html,/data-l="uav" checked/);
assert.match(html,/uav-incidents\.js/);
assert.match(html,/RECOVERED UAV —/);
assert.match(html,/OBSERVED/);
assert.match(html,/ASSESSED/);
assert.match(html,/ATTRIBUTED/);
assert.match(html,/max-height:min\(70vh/);
assert.match(html,/overflow-y:auto/);
assert.match(html,/leaflet-popup-close-button[^}]*[\s\S]*?width:44px/);
assert.match(html,/dynamic-watch-zone/);
assert.match(html,/event-relation/);
assert.match(html,/setInterval\(initEventEngine,60000\)/);
assert.match(html,/RELATED OBSERVATIONS/);
assert.match(sw,/uav-incidents\.js/);
assert.match(sw,/mock\/uav-incidents\.json/);
assert.equal(seed.incidents[0].origin,"UNKNOWN");
assert.equal(seed.incidents[0].attribution.status,"NONE");
assert.equal(seed.incidents[0].explosivePayload,"NO");
console.log("uav integration tests passed");
